spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ASKU-PI/asku-config
          defaultLabel: main
          skipSslValidation: true
  security:
    user:
      password: ${CONFIG_SERVICE_PASSWORD}

server:
  port: 8888
